### ISSUE TITLE
Not compatible with Redmine 4.x

### ISSUE THREAD

**Issue by twkrol** [stgeneral/redmine-progressive-projects-list#86]
Hi
I've recently upgraded to Redmine 4.0.1 and this plugin is not compatible with it (due to Rails incompatibility I think)
Any plans to fix it?
Thanks

**Comment by stgeneral** [comment]
Thank you for reporting this issue. 

Yes, we will fix the issue but can't promise any specific timeline yet.

**Comment by stgeneral** [comment]
By the way, could you please try to install the plugin from the PR #84? This PR contains updates for the compatibility with the newer versions of Ruby. 

Let me know the results, please.

**Comment by twkrol** [comment]
Nope, doesn't work

**Comment by piolty** [comment]
Hi guys, do you have any news about that? Is there anything I can do to integrate it on 4 version? Thanks a lot

**Comment by stgeneral** [comment]
@piolty it's difficult to say. But hope we make the appropriate updates by the end of the year :)

**Comment by dedounet** [comment]
Hi there ! Any news on a compatibility update ? Would be great !

**Comment by stgeneral** [comment]
Still, hope to update it by the end of the year. We have updated it for Redmine 3.4 in #88 and this issue is the next step.

Thanks for keeping asking, it motivates us to deliver updates :)

**Comment by jamasi** [comment]
To motivate you further: I also stumbled on this compatibility issue today and am looking forward to the upcoming fix. 

For reference: This is what I get while trying to run the database migrations while the plugin is installed on Redmine 4.0.5:

```
rake aborted!
NoMethodError: undefined method `alias_method_chain' for ProjectsHelper:Module
Did you mean?  alias_method
/home/redmine/redmine-4.0/plugins/progressive_projects_list/lib/progressive/projects_helper_patch.rb:64:in `block in included'
/home/redmine/redmine-4.0/plugins/progressive_projects_list/lib/progressive/projects_helper_patch.rb:3:in `class_eval'
/home/redmine/redmine-4.0/plugins/progressive_projects_list/lib/progressive/projects_helper_patch.rb:3:in `included'
/home/redmine/redmine-4.0/plugins/progressive_projects_list/lib/progressive/projects_helper_patch.rb:70:in `include'
/home/redmine/redmine-4.0/plugins/progressive_projects_list/lib/progressive/projects_helper_patch.rb:70:in `<top (required)>'
/home/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/home/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/home/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/home/redmine/redmine-4.0/plugins/progressive_projects_list/init.rb:26:in `<top (required)>'
/home/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/home/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/home/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/home/redmine/redmine-4.0/lib/redmine/plugin.rb:175:in `block in load'
/home/redmine/redmine-4.0/lib/redmine/plugin.rb:166:in `each'
/home/redmine/redmine-4.0/lib/redmine/plugin.rb:166:in `load'
/home/redmine/redmine-4.0/config/initializers/30-redmine.rb:21:in `<top (required)>'
/home/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'
/home/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `block in load'
/home/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'
/home/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.3/lib/rails/engine.rb:657:in `block in load_config_initializer'
/home/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.3/lib/active_support/notifications.rb:170:in `instrument'
/home/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.3/lib/rails/engine.rb:656:in `load_config_initializer'
/home/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.3/lib/rails/engine.rb:614:in `block (2 levels) in <class:Engine>'
/home/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.3/lib/rails/engine.rb:613:in `each'
/home/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.3/lib/rails/engine.rb:613:in `block in <class:Engine>'
/home/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `instance_exec'
/home/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `run'
/home/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
/home/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.3/lib/rails/initializable.rb:50:in `each'
/home/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.3/lib/rails/initializable.rb:50:in `tsort_each_child'
/home/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.3/lib/rails/initializable.rb:60:in `run_initializers'
/home/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.3/lib/rails/application.rb:361:in `initialize!'
/home/redmine/redmine-4.0/config/environment.rb:14:in `<top (required)>'
/home/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.3/lib/rails/application.rb:337:in `require'
/home/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.3/lib/rails/application.rb:337:in `require_environment!'
/home/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.3/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/home/redmine/.rvm/gems/ruby-2.6.3/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/home/redmine/.rvm/rubies/ruby-2.6.3/bin/bundle:30:in `block in <main>'
/home/redmine/.rvm/rubies/ruby-2.6.3/bin/bundle:22:in `<main>'
Tasks: TOP => db:migrate => db:load_config => environment

```

**Comment by stgeneral** [comment]
Hey, @twkrol @piolty @dedounet @jamasi and everybody interested, 

Would you like to try the updated version and confirm if it works for you? :)

Updated code in PR #90 and you can [download zip file](https://github.com/stgeneral/redmine-progressive-projects-list/archive/feature/5702-update-to-redmine-4-0-5.zip).

Thank you in advance for the testing and feedback.
